#:package TextMateSharp.Grammars@2.0.4

// Regenerates src/TuiCode.Syntax/Grammars.zip and the grammar section of THIRD-PARTY-NOTICES.md;
// see "Syntax highlighting" in AGENTS.md. Set GITHUB_TOKEN to avoid GitHub's anonymous rate limit.

using System.IO.Compression;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json.Nodes;

const string grammarPrefix = "TextMateSharp.Grammars.Resources.Grammars.";
const string themePrefix = "TextMateSharp.Grammars.Resources.Themes.";
const string manifestSuffix = ".package.json";
const string noticesBegin = "<!-- BEGIN GRAMMARS: generated by scripts/update-grammar-bundle.cs -->";
const string noticesEnd = "<!-- END GRAMMARS -->";

// Only the themes the editor uses; all come from VS Code (MIT, covered in THIRD-PARTY-NOTICES.md).
string[] themes = ["dark_plus.json", "dark_vs.json", "light_plus.json", "light_vs.json"];

var root = Path.GetFullPath(Path.Combine((string)AppContext.GetData("EntryPointFileDirectoryPath")!, ".."));
var assembly = typeof(TextMateSharp.Grammars.RegistryOptions).Assembly;
var resources = assembly.GetManifestResourceNames().ToHashSet(StringComparer.Ordinal);
var entries = new SortedDictionary<string, string>(StringComparer.Ordinal);
var packages = new List<string>();

foreach (var theme in themes)
    entries["themes/" + theme] = themePrefix + theme;

foreach (var resource in resources.Order(StringComparer.Ordinal))
{
    if (!resource.StartsWith(grammarPrefix, StringComparison.Ordinal) || !resource.EndsWith(manifestSuffix, StringComparison.Ordinal))
        continue;

    var package = resource[grammarPrefix.Length..^manifestSuffix.Length];
    packages.Add(package);
    entries[$"grammars/{package}/package.json"] = resource;

    var manifest = JsonNode.Parse(ReadResource(resource))!;
    foreach (var grammar in manifest["contributes"]?["grammars"]?.AsArray() ?? [])
    {
        var path = grammar!["path"]!.GetValue<string>().TrimStart('.', '/');
        var grammarResource = grammarPrefix + package + "." + path.Replace('/', '.');
        // The package only embeds JSON grammars; a few manifests also name plist ones TextMateSharp can't read.
        if (resources.Contains(grammarResource))
            entries[$"grammars/{package}/{path}"] = grammarResource;
        else
            Console.WriteLine($"Skipping {package}/{path}: not embedded in the package");
    }
}

var zipPath = Path.Combine(root, "src", "TuiCode.Syntax", "Grammars.zip");
File.Delete(zipPath);
// Fixed timestamps keep regeneration byte-for-byte reproducible.
var timestamp = new DateTimeOffset(2000, 1, 1, 0, 0, 0, TimeSpan.Zero);
using (var zip = ZipFile.Open(zipPath, ZipArchiveMode.Create))
{
    foreach (var (path, resource) in entries)
    {
        var entry = zip.CreateEntry(path, CompressionLevel.SmallestSize);
        entry.LastWriteTime = timestamp;
        using var source = OpenResource(resource);
        using var target = entry.Open();
        source.CopyTo(target);
    }
}
Console.WriteLine($"Wrote {entries.Count} files to {zipPath} ({new FileInfo(zipPath).Length / 1024} KB)");

using var github = new HttpClient { BaseAddress = new Uri("https://api.github.com/") };
github.DefaultRequestHeaders.UserAgent.ParseAdd("tuicode-update-grammar-bundle");
if (Environment.GetEnvironmentVariable("GITHUB_TOKEN") is { Length: > 0 } token)
    github.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

var components = new Dictionary<string, (JsonNode Registration, List<string> UsedBy)>(StringComparer.OrdinalIgnoreCase);
foreach (var package in packages)
{
    var cgmanifest = grammarPrefix + package + ".cgmanifest.json";
    if (!resources.Contains(cgmanifest))
        throw new InvalidOperationException($"{package} has no cgmanifest.json, so its grammar's license is unknown");
    foreach (var registration in JsonNode.Parse(ReadResource(cgmanifest))!["registrations"]!.AsArray())
    {
        var url = RepositoryUrl(registration!);
        if (!components.TryGetValue(url, out var component))
            components[url] = component = (registration!, []);
        component.UsedBy.Add(package);
    }
}

var notices = new StringBuilder();
notices.AppendLine(noticesBegin);
notices.AppendLine();
foreach (var (url, (registration, usedBy)) in components.OrderBy(c => c.Key, StringComparer.OrdinalIgnoreCase))
{
    var commit = registration["component"]!["git"]?["commitHash"]?.GetValue<string>();
    var license = registration["license"]?.GetValue<string>() ?? "unstated";
    notices.AppendLine($"### {url.Replace("https://github.com/", "")}");
    notices.AppendLine();
    notices.AppendLine($"{url}{(commit is null ? "" : $" at `{commit}`")} — {license}. Used by the `{string.Join("`, `", usedBy)}` grammars.");
    notices.AppendLine();
    notices.AppendLine("```text");
    notices.AppendLine((registration["licenseDetail"] is JsonArray detail
        ? string.Join("\n", detail.Select(line => line!.GetValue<string>()))
        : await FetchLicense(url, commit, license)).TrimEnd());
    notices.AppendLine("```");
    notices.AppendLine();
}
notices.Append(noticesEnd);

var noticesPath = Path.Combine(root, "THIRD-PARTY-NOTICES.md");
var existing = File.ReadAllText(noticesPath);
var begin = existing.IndexOf(noticesBegin, StringComparison.Ordinal);
var end = existing.IndexOf(noticesEnd, StringComparison.Ordinal);
if (begin < 0 || end < begin)
    throw new InvalidOperationException($"THIRD-PARTY-NOTICES.md needs the {noticesBegin} and {noticesEnd} markers");
File.WriteAllText(noticesPath, existing[..begin] + notices.ToString().ReplaceLineEndings("\n") + existing[(end + noticesEnd.Length)..]);
Console.WriteLine($"Wrote notices for {components.Count} grammar sources to {noticesPath}");

async Task<string> FetchLicense(string url, string? commit, string license)
{
    if (!url.StartsWith("https://github.com/", StringComparison.Ordinal))
        throw new InvalidOperationException($"Can't fetch the license for {url}; add a licenseDetail by hand");
    var repo = url["https://github.com/".Length..];

    // The license at the pinned commit, else the default branch's (some repos added LICENSE later).
    var text = await FetchContent($"repos/{repo}/license?ref={commit}") ?? await FetchContent($"repos/{repo}/license");
    if (text is null)
    {
        Console.WriteLine($"WARNING: no license file found for {url}; check it by hand");
        return $"No license file is available upstream (the repository may have been removed). VS Code's cgmanifest.json records this component as {license}.";
    }
    // Apache-2.0 §4(d): a NOTICE file must travel with the work too.
    if (license.StartsWith("Apache", StringComparison.OrdinalIgnoreCase)
        && await FetchContent($"repos/{repo}/contents/NOTICE?ref={commit}") is { } notice)
        text = notice.TrimEnd() + "\n\n" + text;
    return text;
}

async Task<string?> FetchContent(string path)
{
    using var response = await github.GetAsync(path);
    if (response.StatusCode == System.Net.HttpStatusCode.NotFound)
        return null;
    response.EnsureSuccessStatusCode();
    var content = JsonNode.Parse(await response.Content.ReadAsStringAsync())!["content"]!.GetValue<string>();
    return Encoding.UTF8.GetString(Convert.FromBase64String(content.Replace("\n", ""))).TrimStart('\uFEFF').ReplaceLineEndings("\n");
}

static string RepositoryUrl(JsonNode registration)
{
    var component = registration["component"]!;
    var url = (component["git"]?["repositoryUrl"] ?? component["other"]?["downloadUrl"])!.GetValue<string>();
    url = url.Trim().TrimEnd('/');
    return url.EndsWith(".git", StringComparison.Ordinal) ? url[..^4] : url;
}

Stream OpenResource(string name) =>
    assembly.GetManifestResourceStream(name) ?? throw new InvalidOperationException($"Missing resource {name}");

string ReadResource(string name)
{
    using var reader = new StreamReader(OpenResource(name));
    return reader.ReadToEnd();
}
