// Regenerates src/TuiCode.Icons/file-icons.tsv from nvim-web-devicons; see "File icons" in AGENTS.md.
// Bump `commit` to pick up upstream changes. Set GITHUB_TOKEN to avoid GitHub's anonymous rate limit.

using System.Globalization;
using System.Net.Http.Headers;
using System.Text;
using System.Text.RegularExpressions;

const string repo = "nvim-tree/nvim-web-devicons";
const string commit = "914decffe650296c87312c53b7933ecb86718499";

var root = Path.GetFullPath(Path.Combine((string)AppContext.GetData("EntryPointFileDirectoryPath")!, ".."));
using var http = new HttpClient();
http.DefaultRequestHeaders.UserAgent.Add(new ProductInfoHeaderValue("TuiCode", "1.0"));
if (Environment.GetEnvironmentVariable("GITHUB_TOKEN") is { Length: > 0 } token)
    http.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

var entry = new Regex("""\["(?<key>[^"]+)"\]\s*=\s*\{\s*icon\s*=\s*"(?<icon>[^"]+)",\s*color\s*=\s*"#(?<color>[0-9A-Fa-f]{6})""");

var output = new StringBuilder();
output.Append($"# Generated by scripts/update-file-icons.cs from {repo}@{commit} (MIT). Don't edit.\n");
output.Append("# kind\tkey\tcodepoint\tdark\tlight\n");

foreach (var (kind, file) in new[] { ("name", "icons_by_filename.lua"), ("ext", "icons_by_file_extension.lua") })
{
    var dark = await Read("default", file);
    var light = await Read("light", file);
    foreach (var (key, (codepoint, darkColor)) in dark.OrderBy(e => e.Key, StringComparer.Ordinal))
    {
        var lightColor = light.TryGetValue(key, out var l) ? l.Color : darkColor;
        output.Append($"{kind}\t{key}\t{codepoint:x}\t{darkColor}\t{lightColor}\n");
    }
}

var path = Path.Combine(root, "src", "TuiCode.Icons", "file-icons.tsv");
File.WriteAllText(path, output.ToString());
Console.WriteLine($"Wrote {path}");

// Keys are matched case-insensitively. Upstream has a few that differ only by case ("R" and "r");
// like nvim-web-devicons, the lowercase one wins.
async Task<SortedDictionary<string, (int Codepoint, string Color)>> Read(string variant, string file)
{
    var lua = await http.GetStringAsync($"https://raw.githubusercontent.com/{repo}/{commit}/lua/nvim-web-devicons/{variant}/{file}");
    var result = new SortedDictionary<string, (int, string)>(StringComparer.Ordinal);
    foreach (Match m in entry.Matches(lua))
    {
        var key = m.Groups["key"].Value;
        var lower = key.ToLowerInvariant();
        if (key != lower && result.ContainsKey(lower))
            continue;
        var codepoint = char.ConvertToUtf32(m.Groups["icon"].Value, 0);
        result[lower] = (codepoint, m.Groups["color"].Value.ToLower(CultureInfo.InvariantCulture));
    }
    return result;
}
