<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="1.8.5" />
    <PackageReference Include="TestableIO.System.IO.Abstractions.TestingHelpers" Version="22.1.1" />
    <PackageReference Include="xunit.v3" Version="3.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TuiCode.Workbench\TuiCode.Workbench.csproj" />
    <ProjectReference Include="..\..\src\TuiCode.Explorer\TuiCode.Explorer.csproj" />
    <ProjectReference Include="..\..\src\TuiCode.Abstractions\TuiCode.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\TuiCode.Editor\TuiCode.Editor.csproj" />
  </ItemGroup>

</Project>
